### ISSUE TITLE
Create annotation for citations

### ISSUE THREAD

**Issue by felixreimann** [felixreimann/opt4j#8]
A `@citation` annotation shall hold information for citations for a specific class.

When an optimization is started, all used classes with @citation could be gathered and, as an information, printed out to the logger.

The GUI could show them.

**Comment by michaelhglass** [comment]
Possible list of features:
- Multiple citations per class/element required (careful since multiple annotations of the same type requires Java 8 - otherwise a @citations might be required with nested @citation)
- The respective representation of the annotation should follow one internationally accepted style like Harvard etc. I would suggest relying on the programmer to adhere to a certain simple style and not integrate a full-fledged BibTeX/Biber parser
- Citation should also find its way into the documentation without duplicating entries in the comment

**Comment by felixreimann** [comment]
Regarding your first point: I think it is time to upgrade to Java 9. Thus, another @Citations is not necessary.
